//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDbEntities : DbContext
    {
        public ProjectDbEntities()
            : base("name=ProjectDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TCATEGORY> TCATEGORY { get; set; }
        public virtual DbSet<TEMPLOYEEREGION> TEMPLOYEEREGION { get; set; }
        public virtual DbSet<TEMPLOYEES> TEMPLOYEES { get; set; }
        public virtual DbSet<TLOGDATA> TLOGDATA { get; set; }
        public virtual DbSet<TLOGERROR> TLOGERROR { get; set; }
        public virtual DbSet<TLOGLOGIN> TLOGLOGIN { get; set; }
        public virtual DbSet<TLOGTYPE> TLOGTYPE { get; set; }
        public virtual DbSet<TORDERDETAIL> TORDERDETAIL { get; set; }
        public virtual DbSet<TORDERS> TORDERS { get; set; }
        public virtual DbSet<TORDERSTATUS> TORDERSTATUS { get; set; }
        public virtual DbSet<TPRODUCT> TPRODUCT { get; set; }
        public virtual DbSet<TQRCODE> TQRCODE { get; set; }
        public virtual DbSet<TREGION> TREGION { get; set; }
        public virtual DbSet<TREGIONS> TREGIONS { get; set; }
        public virtual DbSet<TSTATUS> TSTATUS { get; set; }
        public virtual DbSet<TTABLE> TTABLE { get; set; }
        public virtual DbSet<TUSERDATA> TUSERDATA { get; set; }
    }
}
