//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCATEGORY()
        {
            this.TPRODUCT = new HashSet<TPRODUCT>();
        }
    
        public int CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string CATEGORY_DESCRIPTION { get; set; }
        public string CATEGORY_IMG { get; set; }
        public Nullable<int> CATEGORY_C_ID { get; set; }
        public Nullable<int> CATEGORY_STATUS { get; set; }
        public Nullable<int> CATEGORY_CREATED_USER_ID { get; set; }
        public Nullable<int> CATEGORY_EDITED_USER_ID { get; set; }
        public Nullable<System.DateTime> CATEGORY_CREATED_DATE { get; set; }
        public Nullable<System.DateTime> CATEGORY_EDITED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPRODUCT> TPRODUCT { get; set; }
    }
}
