//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLOYEEREGION
    {
        public int EMPLOYEEREGION_ID { get; set; }
        public Nullable<int> EMPLOYEEREGION_EMPLOYEE_ID { get; set; }
        public Nullable<int> EMPLOYEEREGION_REGION_ID { get; set; }
        public string EMPLOYEEREGION_DESCRIPTION { get; set; }
        public Nullable<int> EMPLOYEEREGION_C_ID { get; set; }
        public Nullable<int> EMPLOYEEREGION_CREATED_USER_ID { get; set; }
        public Nullable<System.DateTime> EMPLOYEEREGION_CREATED_DATE { get; set; }
        public Nullable<int> EMPLOYEEREGION_EDITED_USER_ID { get; set; }
        public Nullable<System.DateTime> EMPLOYEEREGION_EDITED_DATE { get; set; }
    }
}
