//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLOYEES
    {
        public int EMPLOYEES_ID { get; set; }
        public string EMPLOYEES_NAME { get; set; }
        public string EMPLOYEES_TITLE { get; set; }
        public Nullable<System.DateTime> EMPLOYEES_BIRTHDAY { get; set; }
        public string EMPLOYEES_ADRESS { get; set; }
        public string EMPLOYEES_CITY { get; set; }
        public string EMPLOYEES_REGION { get; set; }
        public string EMPLOYEES_POSTAL_CODE { get; set; }
        public string EMPLOYEES_COUNTRY { get; set; }
        public string EMPLOYEES_PHONE_NUMBER { get; set; }
        public string EMPLOYEES_IMG { get; set; }
        public string EMPLOYEES_DESCRIPTION { get; set; }
        public Nullable<int> EMPLOYEES_C_ID { get; set; }
        public Nullable<int> EMPLOYEES_CREATED_USER_ID { get; set; }
        public Nullable<System.DateTime> EMPLOYEES_CREATED_DATE { get; set; }
        public Nullable<int> EMPLOYEES_EDITED_USER_ID { get; set; }
        public Nullable<System.DateTime> EMPLOYEES_EDITED_DATE { get; set; }
        public Nullable<int> EMPLOYEES_STATUS { get; set; }
    }
}
