//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLOGERROR
    {
        public long LOGERROR_ID { get; set; }
        public Nullable<int> LOGERROR_LOGTYPE_ID { get; set; }
        public string LOGERROR_OPERATION { get; set; }
        public string LOGERROR_MESSAGE { get; set; }
        public Nullable<int> LOGERROR_USER_ID { get; set; }
        public Nullable<System.DateTime> LOGERROR_CREATED_DATE { get; set; }
        public Nullable<int> LOGERROR_C_ID { get; set; }
    }
}
