//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLOGTYPE
    {
        public int LOGTYPE_ID { get; set; }
        public string LOGTYPE_ADI { get; set; }
        public string LOGTYPE_RENK { get; set; }
        public string LOGTYPE_IMG { get; set; }
        public string LOGTYPE_STYLE { get; set; }
    }
}
