//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLOGLOGIN
    {
        public int LOGLOGIN_ID { get; set; }
        public Nullable<int> LOGLOGIN_USER_ID { get; set; }
        public string LOGLOGIN_USER_NAME { get; set; }
        public string LOGLOGIN_IP { get; set; }
        public string LOGLOGIN_BROWSER { get; set; }
        public string LOGLOGIN_OTHER { get; set; }
        public Nullable<System.DateTime> LOGLOGIN_CREATED_DATE { get; set; }
        public string LOGLOGIN_DESCRIPTION { get; set; }
        public Nullable<int> LOGLOGIN_C_ID { get; set; }
    }
}
