//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLOGDATA
    {
        public long LOGS_ID { get; set; }
        public string LOGS_OPERATION { get; set; }
        public Nullable<int> LOGS_USER_ID { get; set; }
        public Nullable<System.DateTime> LOGS_CREATED_DATE { get; set; }
        public Nullable<int> LOGS_C_ID { get; set; }
        public Nullable<int> LOGS_LOGTYPE_ID { get; set; }
    }
}
