//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TORDERS
    {
        public int ORDER_ID { get; set; }
        public Nullable<int> ORDER_CUSTOMER_ID { get; set; }
        public Nullable<int> ORDER_REGION { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<System.DateTime> ORDER_CREATED_DATE { get; set; }
        public Nullable<int> ORDER_C_ID { get; set; }
        public Nullable<int> ORDER_TABLE_ID { get; set; }
        public Nullable<int> ORDER_STATUS_ID { get; set; }
        public Nullable<System.DateTime> ORDERS_GET_READY_DATE { get; set; }
        public Nullable<System.DateTime> ORDERS_DELIVERY_DATE { get; set; }
    }
}
