//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TORDERDETAIL
    {
        public int ORDERDETAIL_ID { get; set; }
        public Nullable<int> ORDERDETAIL_ORDER_ID { get; set; }
        public Nullable<int> ORDERDETAIL_PRODUCT_ID { get; set; }
        public Nullable<decimal> ORDERDETAIL_PRODUCT_PRICE { get; set; }
        public Nullable<int> ORDERDETAIL_QUANTITY { get; set; }
        public Nullable<decimal> ORDERDETAIL_TOTAL_AMOUNT { get; set; }
        public Nullable<int> ORDERDETAIL_C_ID { get; set; }
        public Nullable<int> ORDERDETAIL_STATUS_ID { get; set; }
        public Nullable<System.DateTime> ORDERDETAIL_CREATED_DATE { get; set; }
        public Nullable<System.DateTime> ORDERDETAIL_GET_READY_DATE { get; set; }
        public Nullable<decimal> ORDERDETAIL_DISCOUNT { get; set; }
        public Nullable<System.DateTime> ORDERS_DELIVERY_DATE { get; set; }
    }
}
