//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPRODUCT
    {
        public int PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<int> PRODUCT_CATEGORY_ID { get; set; }
        public string PRODUCT_IMG { get; set; }
        public Nullable<int> PRODUCT_QUANTITY { get; set; }
        public Nullable<decimal> PRODUCT_PRICE { get; set; }
        public string PRODUCT_ORDERNUMBER { get; set; }
        public Nullable<int> PRODUCT_STATUS { get; set; }
        public Nullable<System.DateTime> PRODUCT_CREATED_DATE { get; set; }
        public Nullable<int> PRODUCT_C_ID { get; set; }
        public Nullable<int> PRODUCT_CREATED_USER_ID { get; set; }
        public Nullable<int> PRODUCT_EDITED_USER_ID { get; set; }
        public Nullable<System.DateTime> PRODUCT_EDITED_DATE { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
    
        public virtual TCATEGORY TCATEGORY { get; set; }
    }
}
