//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQRCODE
    {
        public int QRCODE_ID { get; set; }
        public Nullable<int> QRCODE_TABLE_ID { get; set; }
        public Nullable<int> QRCODE_REGION { get; set; }
        public string QRCODE_DESCRİPTİON { get; set; }
        public Nullable<System.DateTime> QRCODE_CREATED_DATE { get; set; }
        public Nullable<int> QRCODE_CREATED_USER_ID { get; set; }
        public Nullable<System.DateTime> QRCODE_EDITED_DATE { get; set; }
        public Nullable<int> QRCODE_EDITED_USER_ID { get; set; }
        public Nullable<int> QRCODE_C_ID { get; set; }
    }
}
