//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREGIONS
    {
        public int REGIONS_ID { get; set; }
        public Nullable<int> REGIONS_REGION_ID { get; set; }
        public string REGIONS_NAME { get; set; }
        public string REGIONS_DESCRIPTION { get; set; }
        public Nullable<int> REGIONS_C_ID { get; set; }
        public Nullable<int> REGIONS_CREATED_USER_ID { get; set; }
        public Nullable<int> REGIONS_EDITED_USER_ID { get; set; }
        public Nullable<System.DateTime> REGIONS_CREATED_DATE { get; set; }
        public Nullable<System.DateTime> REGIONS_EDITED_DATE { get; set; }
        public Nullable<int> REGIONS_STATUS { get; set; }
    
        public virtual TREGION TREGION { get; set; }
    }
}
