//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTABLE
    {
        public int TABLE_ID { get; set; }
        public Nullable<int> TABLE_NUMBER { get; set; }
        public string TABLE_NAME { get; set; }
        public Nullable<int> TABLE_STATUS { get; set; }
        public string TABLE_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> TABLE_CREATED_DATE { get; set; }
        public Nullable<int> TABLE_CREATED_USER_ID { get; set; }
        public Nullable<System.DateTime> TABLE_EDITED_DATE { get; set; }
        public Nullable<int> TABLE_EDITED_USER_ID { get; set; }
        public Nullable<int> TABLE_C_ID { get; set; }
        public string TABLE_QR_CODE { get; set; }
    }
}
