//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exorderproject_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSERDATA
    {
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASS { get; set; }
        public string USER_ADI { get; set; }
        public string USER_SOYADI { get; set; }
        public Nullable<System.DateTime> USER_CREATED_DATE { get; set; }
        public Nullable<byte> USER_AKTIFPASIF_ID { get; set; }
        public Nullable<int> USER_USERDURUM_ID { get; set; }
        public string USER_EMAIL { get; set; }
        public Nullable<int> USER_GURUP_ID { get; set; }
        public string USER_ESKI_PASS { get; set; }
        public Nullable<System.DateTime> USER_PASS_EXPIRE_TRH { get; set; }
        public Nullable<System.DateTime> USER_GIRIS_TARIHI { get; set; }
        public Nullable<int> USER_MM { get; set; }
        public string USER_GOREV { get; set; }
        public string USER_TEL { get; set; }
        public Nullable<System.DateTime> USER_EDITED_DATE { get; set; }
        public Nullable<int> USER_EDITED_USER_ID { get; set; }
        public Nullable<int> USER_CREATED_USER_ID { get; set; }
        public Nullable<int> USER_USERTIPI_ID { get; set; }
        public string USER_IMG { get; set; }
        public Nullable<int> USER_USERDIL_ID { get; set; }
        public string USER_LAST_LOGGED_SESSION { get; set; }
        public Nullable<System.DateTime> USER_LAST_LOGGED_DATE { get; set; }
        public string USER_TEST { get; set; }
        public Nullable<int> USER_C_ID { get; set; }
    }
}
